// Seed data for Nimad ZAYKA Spices
// EAN-13 checksum helper: pass 12 digits, returns 13-digit valid EAN-13
export function ean13(first12) {
  const s = String(first12).padStart(12, '0').slice(0, 12);
  let sum = 0;
  for (let i = 0; i < 12; i++) {
    sum += Number(s[i]) * (i % 2 === 0 ? 1 : 3);
  }
  const check = (10 - (sum % 10)) % 10;
  return s + check;
}

export const seedProducts = [
  // ============ PREMIUM BOX PACKAGING ============
  {
    slug: 'meat-masala',
    name: 'Meat Masala',
    nameHindi: 'मीट मसाला',
    category: 'premium-box',
    tagline: 'Royal Blend for Rich Meat Curries',
    description: 'Our Meat Masala is a royal blend of hand-picked aromatic spices, slow-roasted and stone-ground using traditional Nimadi methods. Perfect for mutton, lamb and red meat curries that taste like grandma made them.',
    ingredients: 'Coriander, Cumin, Black Pepper, Cardamom, Cinnamon, Cloves, Bay Leaves, Nutmeg, Mace, Star Anise, Red Chilli, Turmeric, Dried Ginger, Iodized Salt.',
    usage: 'Add 1-2 teaspoons while cooking meat curries. Best added after the onions turn golden brown for maximum aroma.',
    recipes: 'Classic Mutton Curry, Bhuna Gosht, Mutton Rogan Josh, Keema Masala, Lamb Curry.',
    variants: [
      { weight: '20g', mrp: 30, price: 25, sku: 'NZ-MM-20', barcode: '8901234560201' },
      { weight: '50g', mrp: 75, price: 65, sku: 'NZ-MM-50', barcode: '8901234560501' },
      { weight: '100g', mrp: 145, price: 130, sku: 'NZ-MM-100', barcode: '8901234561001' },
    ],
    tags: ['meat', 'mutton', 'premium', 'box', 'curry'],
    stockStatus: 'in-stock',
  },
  {
    slug: 'garam-masala',
    name: 'Garam Masala',
    nameHindi: 'गरम मसाला',
    category: 'premium-box',
    tagline: 'The Heart of Indian Cuisine',
    description: 'A signature blend of warm, fragrant spices crafted from a time-honored Nimadi recipe. Adds depth, warmth and authentic flavor to every dish.',
    ingredients: 'Coriander, Cumin, Black Cardamom, Green Cardamom, Cinnamon, Cloves, Black Pepper, Bay Leaf, Nutmeg, Mace.',
    usage: 'Sprinkle 1/2 teaspoon at the end of cooking. Use in curries, dals, biryanis and tandoori marinades.',
    recipes: 'Chana Masala, Paneer Butter Masala, Dal Makhani, Chicken Biryani, Tandoori Chicken.',
    variants: [
      { weight: '50g', mrp: 85, price: 75, sku: 'NZ-GM-50', barcode: '8901234570501' },
      { weight: '100g', mrp: 160, price: 145, sku: 'NZ-GM-100', barcode: '8901234571001' },
    ],
    tags: ['garam masala', 'premium', 'box', 'signature'],
    stockStatus: 'in-stock',
  },
  {
    slug: 'shahi-paneer-masala',
    name: 'Shahi Paneer Masala',
    nameHindi: 'शाही पनीर मसाला',
    category: 'premium-box',
    tagline: 'Restaurant-Style Royal Paneer at Home',
    description: 'Bring the magic of royal Mughlai kitchens to your home. A creamy, rich blend designed to give your paneer dishes that signature restaurant-style taste.',
    ingredients: 'Coriander, Cumin, Kasuri Methi, Cardamom, Cinnamon, Cloves, Cashew Powder, Red Chilli, Turmeric, Black Pepper, Salt.',
    usage: 'Add 2 teaspoons to your tomato-onion gravy. Simmer with cream and paneer cubes for 5 minutes.',
    recipes: 'Shahi Paneer, Paneer Pasanda, Paneer Korma, Malai Kofta.',
    variants: [
      { weight: '50g', mrp: 80, price: 70, sku: 'NZ-SP-50', barcode: '8901234580501' },
      { weight: '100g', mrp: 150, price: 135, sku: 'NZ-SP-100', barcode: '8901234581001' },
    ],
    tags: ['paneer', 'shahi', 'premium', 'box', 'mughlai'],
    stockStatus: 'in-stock',
  },
  {
    slug: 'dal-bati-masala',
    name: 'Dal Bati Masala',
    nameHindi: 'दाल बाटी मसाला',
    category: 'premium-box',
    tagline: 'Authentic Nimadi-Malwa Heritage',
    description: 'The soul of every Nimadi household. Our Dal Bati Masala captures the rustic, earthy flavors of Malwa region\'s most beloved dish.',
    ingredients: 'Coriander, Cumin, Fenugreek, Asafoetida, Red Chilli, Turmeric, Dried Mango, Black Salt, Mustard Seeds, Ginger Powder.',
    usage: 'Mix 1 tablespoon into your toor/chana dal. Drizzle ghee with this masala on hot baatis.',
    recipes: 'Dal Bati Churma, Panchmel Dal, Bati with Lehsun Chutney.',
    variants: [
      { weight: '50g', mrp: 70, price: 60, sku: 'NZ-DB-50', barcode: '8901234590501' },
      { weight: '100g', mrp: 130, price: 115, sku: 'NZ-DB-100', barcode: '8901234591001' },
    ],
    tags: ['dal', 'bati', 'nimadi', 'malwa', 'premium', 'box'],
    stockStatus: 'in-stock',
  },
  {
    slug: 'khada-masala',
    name: 'Khada Masala',
    nameHindi: 'खड़ा मसाला',
    category: 'premium-box',
    tagline: 'Whole Spices, Whole Flavor',
    description: 'A premium mix of whole, unground spices in a box with a backside viewing window. Tempers oil with the most aromatic, soul-warming bouquet.',
    ingredients: 'Whole Black Cardamom, Green Cardamom, Cinnamon Sticks, Cloves, Bay Leaves, Star Anise, Black Pepper, Mace, Nutmeg pieces.',
    usage: 'Add to hot oil/ghee at the start of cooking. Sieve before serving or leave for visual appeal in biryanis.',
    recipes: 'Biryani, Pulao, Korma, Nihari, Stews and Slow Cooks.',
    variants: [
      { weight: '50g', mrp: 120, price: 105, sku: 'NZ-KM-50', barcode: '8901234600501' },
      { weight: '100g', mrp: 225, price: 200, sku: 'NZ-KM-100', barcode: '8901234601001' },
    ],
    tags: ['whole', 'khada', 'biryani', 'premium', 'box', 'window'],
    stockStatus: 'in-stock',
  },
  {
    slug: 'chicken-masala',
    name: 'Chicken Masala',
    nameHindi: 'चिकन मसाला',
    category: 'premium-box',
    tagline: 'The Perfect Chicken Curry Companion',
    description: 'Crafted for the perfect home-style chicken curry. Balanced heat, deep aroma and a signature finish that makes every bite memorable.',
    ingredients: 'Coriander, Cumin, Red Chilli, Turmeric, Black Pepper, Garam Masala, Kasuri Methi, Garlic Powder, Ginger Powder, Salt.',
    usage: 'Add 1-2 tablespoons while sauteing chicken with onion-tomato base. Cook covered for 20 minutes.',
    recipes: 'Butter Chicken, Chicken Tikka Masala, Kadhai Chicken, Chicken Curry.',
    variants: [
      { weight: '20g', mrp: 28, price: 24, sku: 'NZ-CM-20', barcode: '8901234610201' },
      { weight: '50g', mrp: 70, price: 60, sku: 'NZ-CM-50', barcode: '8901234610501' },
      { weight: '100g', mrp: 135, price: 120, sku: 'NZ-CM-100', barcode: '8901234611001' },
    ],
    tags: ['chicken', 'premium', 'box', 'curry'],
    stockStatus: 'in-stock',
  },
  // ============ STANDARD PLASTIC PACKAGING ============
  {
    slug: 'haldi-powder',
    name: 'Haldi Powder (Turmeric)',
    nameHindi: 'हल्दी पाउडर',
    category: 'standard-plastic',
    tagline: 'Pure Golden Goodness',
    description: '100% pure turmeric powder sourced from the finest farms of Nimad region. High curcumin content, rich golden color and authentic earthy aroma.',
    ingredients: 'Pure Turmeric (Curcuma longa). No additives. No artificial colors. No preservatives.',
    usage: 'Use 1/2 to 1 teaspoon in everyday cooking. Also great in golden milk, face packs and home remedies.',
    recipes: 'Use in Sabzi, Dal, Curries, Marinades, Golden Milk (Haldi Doodh).',
    variants: [
      { weight: '50g', mrp: 35, price: 30, sku: 'NZ-HP-50', barcode: '8901234620501' },
      { weight: '100g', mrp: 65, price: 55, sku: 'NZ-HP-100', barcode: '8901234621001' },
      { weight: '200g', mrp: 125, price: 110, sku: 'NZ-HP-200', barcode: '8901234622001' },
      { weight: '500g', mrp: 300, price: 270, sku: 'NZ-HP-500', barcode: '8901234625001' },
      { weight: '1kg', mrp: 580, price: 520, sku: 'NZ-HP-1KG', barcode: '8901234629999' },
    ],
    tags: ['turmeric', 'haldi', 'pure', 'standard'],
    stockStatus: 'in-stock',
  },
  {
    slug: 'lal-mirch-powder',
    name: 'Mirchi Powder (Chilli)',
    nameHindi: 'लाल मिर्च पाउडर',
    category: 'standard-plastic',
    tagline: 'Fiery Red, Bold Flavor',
    description: 'Bold, vibrant red chilli powder ground from sun-dried Nimadi red chillies. Perfect balance of color, heat and aroma.',
    ingredients: 'Pure Red Chilli (Capsicum annuum). No additives or fillers.',
    usage: 'Add 1/2 to 1 teaspoon as per taste in curries, marinades and spice mixes.',
    recipes: 'Use in all spicy curries, Tandoori marinades, Chutneys, Pickles.',
    variants: [
      { weight: '50g', mrp: 40, price: 35, sku: 'NZ-LM-50', barcode: '8901234630501' },
      { weight: '100g', mrp: 75, price: 65, sku: 'NZ-LM-100', barcode: '8901234631001' },
      { weight: '200g', mrp: 145, price: 130, sku: 'NZ-LM-200', barcode: '8901234632001' },
      { weight: '500g', mrp: 350, price: 320, sku: 'NZ-LM-500', barcode: '8901234635001' },
      { weight: '1kg', mrp: 680, price: 620, sku: 'NZ-LM-1KG', barcode: '8901234639999' },
    ],
    tags: ['chilli', 'mirchi', 'red', 'pure', 'standard'],
    stockStatus: 'in-stock',
  },
  {
    slug: 'dhaniya-powder',
    name: 'Dhaniya Powder (Coriander)',
    nameHindi: 'धनिया पाउडर',
    category: 'standard-plastic',
    tagline: 'The Foundation of Indian Cooking',
    description: 'Aromatic, fresh-ground coriander powder from premium-grade seeds. Adds a sweet, citrusy depth to your daily cooking.',
    ingredients: 'Pure Coriander Seeds (Coriandrum sativum). 100% natural.',
    usage: 'Use 1-2 teaspoons in tadka, masalas and gravies. Essential in every Indian kitchen.',
    recipes: 'Use in Sabzi, Dal Tadka, Curries, Spice Mixes, Chutneys.',
    variants: [
      { weight: '50g', mrp: 35, price: 30, sku: 'NZ-DP-50', barcode: '8901234640501' },
      { weight: '100g', mrp: 65, price: 55, sku: 'NZ-DP-100', barcode: '8901234641001' },
      { weight: '200g', mrp: 125, price: 110, sku: 'NZ-DP-200', barcode: '8901234642001' },
      { weight: '500g', mrp: 300, price: 270, sku: 'NZ-DP-500', barcode: '8901234645001' },
      { weight: '1kg', mrp: 580, price: 520, sku: 'NZ-DP-1KG', barcode: '8901234649999' },
    ],
    tags: ['coriander', 'dhaniya', 'pure', 'standard'],
    stockStatus: 'in-stock',
  },
  {
    slug: 'garam-masala-standard',
    name: 'Garam Masala (Standard)',
    nameHindi: 'गरम मसाला',
    category: 'standard-plastic',
    tagline: 'Daily Kitchen Essential',
    description: 'A versatile garam masala blend in convenient family-sized packs. Perfect for everyday Indian cooking.',
    ingredients: 'Coriander, Cumin, Cardamom, Cinnamon, Cloves, Black Pepper, Bay Leaves.',
    usage: 'Add 1/2 teaspoon at the end of cooking for warmth and aroma.',
    recipes: 'Use in Sabzi, Dal, Curries, Pulao, Marinades.',
    variants: [
      { weight: '50g', mrp: 75, price: 65, sku: 'NZ-GMS-50', barcode: '8901234650501' },
      { weight: '100g', mrp: 140, price: 125, sku: 'NZ-GMS-100', barcode: '8901234651001' },
      { weight: '200g', mrp: 270, price: 240, sku: 'NZ-GMS-200', barcode: '8901234652001' },
      { weight: '500g', mrp: 650, price: 580, sku: 'NZ-GMS-500', barcode: '8901234655001' },
      { weight: '1kg', mrp: 1250, price: 1100, sku: 'NZ-GMS-1KG', barcode: '8901234659999' },
    ],
    tags: ['garam masala', 'standard', 'daily'],
    stockStatus: 'in-stock',
  },
];

export const brandInfo = {
  name: 'Nimad ZAYKA',
  fullName: 'Nimad ZAYKA Spices',
  tagline: 'Swaad jo Nimad se aayo',
  taglineEn: 'The Taste that Comes from Nimad',
  whatsapp: '916265996333',
  phone: '+91 6265996333',
  instagram: 'https://www.instagram.com/nimadzayka.in',
  instagramHandle: '@nimadzayka.in',
  email: 'info@nimadzayka.com',
  website: 'www.nimadzayka.com',
  fssai: '21426870000005',
  addressMfg: 'Julwaniya Road, Rajpur, Dist. Barwani, Madhya Pradesh - 451447',
  addressOffice: '975, Scheme No. 51, Indore, Madhya Pradesh - 452006',
};
